# Generated by Django 4.0.5 on 2022-06-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_department_alter_books_id_alter_books_publishertime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(max_length=255, verbose_name='图书名字'),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=255, verbose_name='图书编号'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publishertime',
            field=models.CharField(default=3, max_length=255, verbose_name='出版时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
