# Generated by Django 4.0.5 on 2022-06-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_remove_department_id_alter_books_bookname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='picture',
            field=models.ImageField(default='pic.png', upload_to='D:\\keshe02\\TTT\\picture'),
        ),
    ]
