# Generated by Django 4.0.5 on 2022-06-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_alter_books_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='picture',
        ),
    ]
