# Generated by Django 4.0.5 on 2022-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_remove_books_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='用户头像'),
        ),
    ]
