# Generated by Django 4.0.5 on 2022-06-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_rename_avatar_books_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='picture',
            field=models.CharField(max_length=255, verbose_name='图片'),
        ),
    ]
