# Generated by Django 4.0.5 on 2022-06-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_alter_books_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='picture',
            new_name='picture1',
        ),
    ]
