# Generated by Django 4.0.5 on 2022-06-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_rename_picture_books_picture1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='picture1',
        ),
        migrations.AddField(
            model_name='books',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='users', verbose_name='用户头像'),
        ),
    ]
